### ISSUE TITLE
Viewmodel changes color if you die

### ISSUE THREAD

**Issue by NovaAstral** [AlicornLunaa/GrapplingHook#2]
The player's viewmodel changes color if you die while holding a colored grappling hook (The color changes to the grapple's color)
The player can fix this by taking out any grapple hook again.

**Comment by AlicornLunaa** [comment]
I cant seem to reproduce this bug, can you send a video or something?

**Comment by NovaAstral** [comment]
I can't actually reproduce it anymore either after restarting my game, not sure what was going on there.
